# Site settings
title: Pedro Costa
header-img: img/home-bg.jpg
email: pedro.vendascosta@gmail.com
copyright_name:
description: "A blog about Machine Learning and Computer Vision"
baseurl: ""
url: "http://costapt.github.io/"
twitter_username: costapt20
github_username:  costapt
linkedin_username: pedro-costa-361a2984
facebook_username:
email_username:  pedro.vendascosta@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
